/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOBUFS_MOVE_PB_H_INCLUDED
#define PB_PROTOBUFS_MOVE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _moveTo {
    int32_t azimuth;
    int32_t altitude;
    bool has_accelRate;
    int32_t accelRate;
    bool has_speedRate;
    int32_t speedRate;
} moveTo;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define moveTo_init_default                      {0, 0, false, 0, false, 0}
#define moveTo_init_zero                         {0, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define moveTo_azimuth_tag                       1
#define moveTo_altitude_tag                      2
#define moveTo_accelRate_tag                     3
#define moveTo_speedRate_tag                     4

/* Struct field encoding specification for nanopb */
#define moveTo_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    azimuth,           1) \
X(a, STATIC,   REQUIRED, INT32,    altitude,          2) \
X(a, STATIC,   OPTIONAL, INT32,    accelRate,         3) \
X(a, STATIC,   OPTIONAL, INT32,    speedRate,         4)
#define moveTo_CALLBACK NULL
#define moveTo_DEFAULT NULL

extern const pb_msgdesc_t moveTo_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define moveTo_fields &moveTo_msg

/* Maximum encoded size of messages (where known) */
#define PROTOBUFS_MOVE_PB_H_MAX_SIZE             moveTo_size
#define moveTo_size                              44

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
